### ISSUE TITLE
Renomear os arquivos

### ISSUE THREAD

**Issue by JoaoPedro-Correia** [moreiracodes/Aprenda-Vim#3]
Reparei que você não está traduzindo os nomes dos arquivos, você pretende manter eles originais ou fazer a tradução?

**Comment by moreiracodes** [comment]
Respondido no [PR 02](https://github.com/moreiracodes/Aprenda-Vim/pull/2#issuecomment-1863609880)

**Comment by moreiracodes** [comment]
issue fechada
